update readme for configuration file analysis
aicoe-aiops/configuration-files-analysis pull request #9
Opened 2020-10-12 18:06 UTC by SankBad

This PR will update the README of the repository. Closes #3

2020-10-12 21:12 UTC, Shreyanand requested changes
LGTM, minor change

2020-10-12 21:12 UTC, Shreyanand commented on README.md
> +Today's software system became more flexible and feature-rich. For example, the configuration file for MySQL has more than 200 configuration entries with different subentries.  As a result, configuri
Software systems have become more flexible and feature-rich. ...

2020-10-12 21:21 UTC, SankBad commented
Thanks for the feedback @Shreyanand :smile: 
I fixed a typo.

2020-10-12 21:21 UTC, SankBad commented
Also, squashed commits.

2020-10-13 13:51 UTC, Shreyanand approved these changes
:rocket:

2020-10-13 13:51 UTC, merged